DRAW_GRID = True
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 1000
MAXIMIZED_WINDOW_WIDTH = 2520
MAXIMIZED_WINDOW_HEIGHT = 1360
SQ_SIZE = 40

FPS = 15
SQ_WIDTH = WINDOW_WIDTH / SQ_SIZE
SQ_HEIGHT = WINDOW_HEIGHT / SQ_SIZE
SNAKE_INIT_LEN = 3
